version: '3.8'
services:
  mongodb:
    image: mongo:6-jammy
    ports:
      - '27017:27017'

  ollama:  # New service for running the Dockerfile in /ollama
    image: ollama/ollama:latest
    container_name: ollama
    ports: ["11435:11434"] # will be accessible in http://localhost:11435
    tty: true
    volumes:
      - ./model_files:/model_files
    entrypoint: ["/bin/sh", "/model_files/run_ollama.sh"] # Loading the finetuned Mistral with the GGUF file

  server:
    build: .
    command: uvicorn apps:app --reload --host 0.0.0.0 --port 8000
    ports:
      - 8000:8000
    # environment:
    #   - database_uri=postgresql://movie_db_username:movie_db_password@movie_db/movie_db_dev
    #   - cast_service_host_url=http://cast_service:8000/api/v1/casts/
    depends_on:
      - mongodb
      - ollama
