import enum


class DivisionTypeEnum(enum.Enum):
    CONFERENCE = "CONFERENCE"
    ACCOUNT = "ACCOUNT"
    CAFETERIA = "CAFETERIA"
    AMENITY = "AMENITY"
    BANK = "BANK"
    ATM = "ATM"
    STORE = "STORE"
    TECH_BAR = "TECH_BAR"
    SECURITY = "SECURITY"
    RECREATION = "RECREATION"
    GYM = "GYM"
    INSURANCE = "INSURANCE"
    HR = "HR"
    HEALTH = "HEALTH"
    FOUNDERS_HALL = "FOUNDERS_HALL"
    MAIN_LOBBY = "MAIN_LOBBY"
    PLACE = "PLACE"
    PEOPLE = "PEOPLE"
    FLOOR = "FLOOR"
