import enum


class JobDomainEnum(enum.Enum):
    HR = "HR"
    DEVOPS_ENGINEER = "DEVOPS"
    SOFTWARE_ENGINEER = "SOFTWARE"
    FRONTEND_DEVELOPER = "FRONTEND"
    BACKEND_DEVELOPER = "BACKEND"
    FULL_STACK_DEVELOPER = "FULL STACK"
    ANALYST = "ANALYST"
    TEST_ENGINEER = "TEST"
    PRODUCT_MANAGER = "PRODUCT MANAGER"
    ENGINEERING_MANAGER = "ENGINEERING MANAGER"
    TEAM_LEAD = "TEAM LEAD"
    MACHINE_LEARNING_ENGINEER = "MACHINE LEARNING"
    SECURITY_ENGINEER = "SECURITY"
    DATA_ENGINEER = "DATA ENGINEER"
    ANDROID_ENGINEER = "ANDROID"
    IOS_ENGINEER = "iOS"
